export const food_data = [
    {
        'name': 'Apple',
        'category': '',
        'size': '100',
        'calories': '57',
        'protein': '0.25',
        'carbs': '13.68',
        'fat': '0.12',
        'sat_fat': '0',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '2.3',
        'sugar': '10.37',
        'added_sugar': '0',
        'vitamin_a': '28.00',
        'vitamin_b': '0',
        'vitamin_c': '0',
        'vitamin_d': '0',
        'vitamin_e': '0.18',
        'calcium': '7.00',
        'iron': '0.12',
        'potassium': '108.00',
        'sodium': '1.00',
        'fact': 'Apples float in water',
        'fiction': ['All apples have red skin', 'Apples are native to North America', 'Apple cores are the healthiest part of the apple to eat'],
        'export': 'China',
        'exports': ['Italy', 'United States', 'New Zealand'],
        'import': 'Russia',
        'imports': ['Germany', 'United Kingdom', 'Netherlands'],
        'food': 'Waldorf Salad',
        'foods': ['Shepherds Pie', 'Hawaiian Pizza', 'Barbeque Sauce'],
    },
    {
        'name': 'Banana',
        'category': '',
        'size': '100',
        'calories': '89',
        'protein': '1.09',
        'carbs': '22.84',
        'fat': '0.33',
        'sat_fat': '0.112',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '2.6',
        'sugar': '12.23',
        'added_sugar': '0',
        'vitamin_a': '64.00',
        'vitamin_b': '0.00',
        'vitamin_c': '8.7',
        'vitamin_d': '0.00',
        'vitamin_e': '0.10',
        'calcium': '5.00',
        'iron': '0.26',
        'potassium': '358.00',
        'sodium': '1.00',
        'fact': 'Bananas are berries',
        'fiction': ['Bananas are poisonous if eaten before they turn completely yellow', 'Bananas are the only fruit that contains no natural sugar', 'Bananas are radioactive due to their potassium content'],
        'export': 'Ecuador',
        'exports': ['Philippines', 'Guatemala', 'Costa Rica'],
        'import': 'United States',
        'imports': ['China', 'Germany', 'Japan'],
        'food': 'Ginanggang',
        'foods': ['Panna Cotta', 'Mango Lassi', 'Creme Brulee'],
    },
    {
        'name': 'Bread',
        'category': '',
        'size': '100',
        'calories': '267',
        'protein': '10.72',
        'carbs': '48.68',
        'fat': '3.24',
        'sat_fat': '0.777',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '4.0',
        'sugar': '5.91',
        'added_sugar': '0',
        'vitamin_a': '2.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.2',
        'vitamin_d': '0.00',
        'vitamin_e': '0.19',
        'calcium': '133.00',
        'iron': '3.49',
        'potassium': '177.00',
        'sodium': '508.00',
        'fact': 'Bread has been a staple food for thousands of years',
        'fiction': ['All bread contains gluten', 'Bread is bad for digestion', 'Bread is always high in carbs'],
        'export': 'Germany',
        'exports': ['Canada', 'Poland', 'Netherlands'],
        'import': 'United States',
        'imports': ['United Kingdom', 'Germany', 'Canada'],
        'food': 'Croque Madame',
        'foods': ['Nasi Lemak', 'Fish and Chips', 'Latke'],
    },
    {
        'name': 'Butter (Salted)',
        'category': '',
        'size': '100',
        'calories': '717',
        'protein': '0.85',
        'carbs': '0.06',
        'fat': '81.11',
        'sat_fat': '51.368',
        'trans_fat': '0',
        'cholesterol': '215',
        'fiber': '0.0',
        'sugar': '0.06',
        'added_sugar': '0',
        'vitamin_a': '2499.00',
        'vitamin_b': '0.17',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '2.32',
        'calcium': '24.00',
        'iron': '0.02',
        'potassium': '24.00',
        'sodium': '643.00',
        'fact': 'Butter was used as a lubricant in ancient times',
        'fiction': ['Butter can be used as a substitute for engine oil', 'Butter has been used historically as a form of currency', 'Butter has no expiration date'],
        'export': 'New Zealand',
        'exports': ['Ireland', 'Germany', 'Netherlands'],
        'import': 'France',
        'imports': ['Germany', 'Netherlands', 'China'],
        'food': 'Kaya Toast',
        'foods': ['Pizza', 'Fried Rica', 'Kalbi'],
    },
    {
        'name': 'Cheerios',
        'category': '',
        'size': '100',
        'calories': '376',
        'protein': '12.09',
        'carbs': '73.23',
        'fat': '6.73',
        'sat_fat': '1.500',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '9.4',
        'sugar': '4.36',
        'added_sugar': '0',
        'vitamin_a': '3299.00',
        'vitamin_b': '6.77',
        'vitamin_c': '21.6',
        'vitamin_d': '136.00',
        'vitamin_e': '0.65',
        'calcium': '401.00',
        'iron': '33.17',
        'potassium': '641.00',
        'sodium': '497.00',
        'fact': 'Cheerios were originally called CheeriOats',
        'fiction': ['The "O" shape of Cheerios was inspired by the rings of Saturn', 'The Cheerios mascot, Buzz, is based on a real-life astronaut who landed on the moon', 'Cheerios were originally intended as dog food but became popular with humans'],
        'export': 'United States',
        'exports': ['Germany', 'Canada', 'Chile'],
        'import': 'United States',
        'imports': ['Canada', 'Germany', 'France'],
        'food': 'Cereal Squares',
        'foods': ['Rice Krispie Treats', 'Energy Bars', 'Pigs in a Blanket'],
    },
    {
        'name': 'Chicken Tenders',
        'category': '',
        'size': '100',
        'calories': '271',
        'protein': '19.22',
        'carbs': '17.25',
        'fat': '13.95',
        'sat_fat': '2.493',
        'trans_fat': '0',
        'cholesterol': '48',
        'fiber': '1.2',
        'sugar': '0.40',
        'added_sugar': '0',
        'vitamin_a': '11.00',
        'vitamin_b': '0.16',
        'vitamin_c': '1.1',
        'vitamin_d': '7.00',
        'vitamin_e': '3.17',
        'calcium': '17.00',
        'iron': '0.73',
        'potassium': '373.00',
        'sodium': '769.00',
        'fact': 'Chicken tenders are also known as chicken fingers or chicken strips',
        'fiction': ['There is an annual Chicken Finger Festival', 'Chicken tenders were originally invented as a healthy snack for children', 'Chicken tenders are a symbol of peace and harmony'],
        'export': 'Brazil',
        'exports': ['United States', 'Poland', 'Netherlands'],
        'import': 'China',
        'imports': ['Germany', 'France', 'United Kingdom'],
        'food': 'Popeyes',
        'foods': ['Burger King', 'Cava', 'Pizza Hut'],
    },
    {
        'name': 'Egg (Scrambled)',
        'category': '',
        'size': '100',
        'calories': '149',
        'protein': '9.99',
        'carbs': '1.61',
        'fat': '10.98',
        'sat_fat': '3.331',
        'trans_fat': '0',
        'cholesterol': '277',
        'fiber': '0.0',
        'sugar': '1.39',
        'added_sugar': '0',
        'vitamin_a': '578.00',
        'vitamin_b': '0.76',
        'vitamin_c': '0.0',
        'vitamin_d': '72.00',
        'vitamin_e': '1.15',
        'calcium': '66.00',
        'iron': '1.31',
        'potassium': '132.00',
        'sodium': '145.00',
        'fact': 'Scrambled eggs have been a popular dish for centuries',
        'fiction': ['Adding sugar to scrambled eggs enhances their flavor and texture', 'Scrambled eggs were once considered a luxury food', 'Scrambled eggs can be used as a natural dye for coloring fabrics'],
        'export': 'Netherlands',
        'exports': ['United States', 'Poland', 'Turkey'],
        'import': 'Germany',
        'imports': ['Netherlands', 'United Kingdom', 'Canada'],
        'food': 'Breakfast Sandwich',
        'foods': ['Pancakes', 'Ramen', 'Pizza'],
    },
    {
        'name': 'Greek Yogurt',
        'category': '',
        'size': '100',
        'calories': '97',
        'protein': '9.00',
        'carbs': '3.98',
        'fat': '5.00',
        'sat_fat': '2.395',
        'trans_fat': '0',
        'cholesterol': '13',
        'fiber': '0.0',
        'sugar': '4.00',
        'added_sugar': '0',
        'vitamin_a': '15.00',
        'vitamin_b': '0.75',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.01',
        'calcium': '100.00',
        'iron': '0.00',
        'potassium': '141.00',
        'sodium': '35.00',
        'fact': 'Greek yogurt has a significantly higher protein content compared to regular yogurt',
        'fiction': ['Greek yogurt is always made from sheep milk', 'Greek yogurt is not suitable for vegetarians', 'Greek yogurt is actually made in Greece'],
        'export': 'Germany',
        'exports': ['Saudi Arabia', 'France', 'Greece'],
        'import': 'Italy',
        'imports': ['Spain', 'United Kingdom', 'Netherlands'],
        'food': 'Tzatziki',
        'foods': ['Tahini', 'Creme Fraiche', 'Hummus'],
    },
    {
        'name': 'Ground Beef',
        'category': '',
        'size': '100',
        'calories': '198',
        'protein': '19.42',
        'carbs': '0.00',
        'fat': '12.73',
        'sat_fat': '5.335',
        'trans_fat': '0',
        'cholesterol': '62',
        'fiber': '0.0',
        'sugar': '0.00',
        'added_sugar': '0',
        'vitamin_a': '0.00',
        'vitamin_b': '1.97',
        'vitamin_c': '0.0',
        'vitamin_d': '0',
        'vitamin_e': '0.35',
        'calcium': '12.00',
        'iron': '1.99',
        'potassium': '289.00',
        'sodium': '68.00',
        'fact': 'Ground beef is a great source of high-quality protein',
        'fiction': ['Ground beef is always high in fat and calories', 'Ground beef is always made from the meat of one specific type of cow', 'Ground beef is naturally blue in color'],
        'export': 'Brazil',
        'exports': ['United States', 'India', 'Australia'],
        'import': 'China',
        'imports': ['United States', 'Japan', 'South Korea'],
        'food': 'Hamburger',
        'foods': ['Giniling', 'Steak Frites', 'Hot Dog'],
    },
    {
        'name': 'Hummus',
        'category': '',
        'size': '100',
        'calories': '177',
        'protein': '4.86',
        'carbs': '20.12',
        'fat': '8.59',
        'sat_fat': '1.141',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '4.0',
        'sugar': '0.27',
        'added_sugar': '0',
        'vitamin_a': '5.00',
        'vitamin_b': '0.00',
        'vitamin_c': '7.9',
        'vitamin_d': '0.00',
        'vitamin_e': '0.75',
        'calcium': '49.00',
        'iron': '1.56',
        'potassium': '173.00',
        'sodium': '242.00',
        'fact': 'Hummus comes from the Arabic word meaning chickpeas',
        'fiction': ['Hummus is made from mashed chickpeas and yogurt', 'Hummus originated in South America', 'Hummus is not suitable for vegans'],
        'export': 'Australia',
        'exports': ['India', 'Canada', 'Turkey'],
        'import': 'Pakistan',
        'imports': ['Bangladesh', 'United Arab Emirates', 'Turkey'],
        'food': 'Falafel Bowl',
        'foods': ['Butter Chicken', 'Shakshuka', 'Poke Bowl'],
    },
    {
        'name': 'Kimchi',
        'category': '',
        'size': '100',
        'calories': '15',
        'protein': '1.10',
        'carbs': '2.40',
        'fat': '0.50',
        'sat_fat': '0.067',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '1.6',
        'sugar': '1.06',
        'added_sugar': '0',
        'vitamin_a': '93.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.11',
        'calcium': '33.00',
        'iron': '2.50',
        'potassium': '151.00',
        'sodium': '498.00',
        'fact': 'Kimchi  is rich in vitamins A and C',
        'fiction': ['Kimchi was originally created as a vegan alternative to meat dishes in Korea', 'Kimchi is only eaten during specific seasons and not available year-round', 'Kimchi is typically consumed as a dessert in Korean cuisine'],
        'export': 'South Korea',
        'exports': ['United States', 'Japan', 'China'],
        'import': 'United States',
        'imports': ['China', 'Japan', 'Indonesia'],
        'food': 'Korean Barbeque',
        'foods': ['Hot Pot', 'Pho', 'Udon'],
    },
    {
        'name': 'MMs (Milk Chocolate)',
        'category': '',
        'size': '100',
        'calories': '492',
        'protein': '4.33',
        'carbs': '71.19',
        'fat': '21.13',
        'sat_fat': '13.080',
        'trans_fat': '0',
        'cholesterol': '14',
        'fiber': '2.8',
        'sugar': '63.68',
        'added_sugar': '0',
        'vitamin_a': '187.00',
        'vitamin_b': '0.53',
        'vitamin_c': '0.5',
        'vitamin_d': '0.00',
        'vitamin_e': '0.36',
        'calcium': '105.00',
        'iron': '1.11',
        'potassium': '261.00',
        'sodium': '61.00',
        'fact': 'M&M stands for Mars and Murrie, the last names of its founders',
        'fiction': ['M&Ms were originally developed as a space food for astronauts', 'The colors of M&Ms have different flavors', 'M&Ms were banned in certain countries due to their addictive nature'],
        'export': 'United States',
        'exports': ['Germany', 'China', 'Mexico'],
        'import': 'Germany',
        'imports': ['Belgium', 'Italy', 'Poland'],
        'food': 'Candy Cookies',
        'foods': ['Chocolate Tart', 'Chocolate Lava Cake', 'Brownies'],
    },
    {
        'name': 'MMs (Peanut)',
        'category': '',
        'size': '100',
        'calories': '515',
        'protein': '9.57',
        'carbs': '60.48',
        'fat': '26.13',
        'sat_fat': '10.169',
        'trans_fat': '0',
        'cholesterol': '8',
        'fiber': '3.7',
        'sugar': '50.75',
        'added_sugar': '0',
        'vitamin_a': '74.00',
        'vitamin_b': '0.32',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '2.85',
        'calcium': '102.00',
        'iron': '1.16',
        'potassium': '347.00',
        'sodium': '50.00',
        'fact': 'The colors of the peanut M&Ms were originally brown, yellow, and red',
        'fiction': ['Peanut M&Ms were featured in a famous art heist where they were stolen and replaced with regular peanuts', 'Eating Peanut M&Ms while studying can improve memory and cognitive function', 'Each color of the Peanut M&Ms candy shell represents a different flavor'],
        'export': 'United States',
        'exports': ['Germany', 'China', 'Mexico'],
        'import': 'Germany',
        'imports': ['Belgium', 'Italy', 'Poland'],
        'food': 'Candy Cookies',
        'foods': ['Chocolate Tart', 'Chocolate Lava Cake', 'Brownies'],
    },
    {
        'name': 'Orange',
        'category': '',
        'size': '100',
        'calories': '49',
        'protein': '0.91',
        'carbs': '12.54',
        'fat': '0.15',
        'sat_fat': '0.017',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '2.2',
        'sugar': '8.50',
        'added_sugar': '0',
        'vitamin_a': '247.00',
        'vitamin_b': '0.00',
        'vitamin_c': '59.1',
        'vitamin_d': '0.00',
        'vitamin_e': '0.15',
        'calcium': '43.00',
        'iron': '0.13',
        'potassium': '166.00',
        'sodium': '1.00',
        'fact': 'The color orange was named after the fruit',
        'fiction': ['Orange trees cannot survive in temperate regions', 'Oranges evolved from bananas millions of years ago', 'Eating too many oranges can turn your skin orange'],
        'export': 'Spain',
        'exports': ['South Africa', 'Egypt', 'United States'],
        'import': 'Germany',
        'imports': ['Netherlands', 'United States', 'Canada'],
        'food': 'Marmalade',
        'foods': ['Tiramisu', 'Cobb Salad', 'Pita Wrap'],
    },
    {
        'name': 'Pasta (Dry)',
        'category': '',
        'size': '100',
        'calories': '371',
        'protein': '13.04',
        'carbs': '74.67',
        'fat': '1.51',
        'sat_fat': '0.277',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '3.2',
        'sugar': '2.67',
        'added_sugar': '0',
        'vitamin_a': '0.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.11',
        'calcium': '21.00',
        'iron': '1.30',
        'potassium': '223.00',
        'sodium': '6.00',
        'fact': 'Italy is the largest producer of pasta globally',
        'fiction': ['Pasta was invented by Italian monks seeking a way to create edible beads', 'Pasta was once used as currency in Rome', 'Pasta was originally eaten with spoons'],
        'export': 'Italy',
        'exports': ['China', 'South Korea', 'Turkey'],
        'import': 'Mexico',
        'imports': ['Uzbekistan', 'Chile', 'Russia'],
        'food': 'Carbonara',
        'foods': ['Nasi Lemak', 'Croque Madame', 'Xiao Long Bao'],
    },
    {
        'name': 'Rice (Brown, Cooked)',
        'category': '',
        'size': '100',
        'calories': '112',
        'protein': '2.32',
        'carbs': '23.51',
        'fat': '0.83',
        'sat_fat': '0.165',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '1.8',
        'sugar': '0',
        'added_sugar': '0',
        'vitamin_a': '0.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0',
        'calcium': '10.00',
        'iron': '0.53',
        'potassium': '79.00',
        'sodium': '1.00',
        'fact': 'Brown rice has a lower glycemic index compared to white rice',
        'fiction': ['Brown rice has significantly more calories than white rice', 'Cooking brown rice always takes longer than cooking white rice', 'Brown rice is always healthier than white rice'],
        'export': 'India',
        'exports': ['Thailand', 'Vietnam', 'Pakistan'],
        'import': 'Philippines',
        'imports': ['China', 'Indonesia', 'Nigeria'],
        'food': 'Stir Fry',
        'foods': ['Pho', 'Laksa', 'Cuy'],
    },
    {
        'name': 'Rice (White, Cooked)',
        'category': '',
        'size': '100',
        'calories': '130',
        'protein': '2.36',
        'carbs': '28.73',
        'fat': '0.19',
        'sat_fat': '0.051',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '0',
        'sugar': '0',
        'added_sugar': '0',
        'vitamin_a': '0',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0',
        'calcium': '1.00',
        'iron': '0.20',
        'potassium': '26.00',
        'sodium': '0.00',
        'fact': 'White rice has a milder flavor and softer texture compared to brown rice',
        'fiction': ['White rice has a high protein content', 'White rice is made from wheat grains', 'White rice is always sticky and clumpy when cooked'],
        'export': 'India',
        'exports': ['Thailand', 'Vietnam', 'Pakistan'],
        'import': 'Philippines',
        'imports': ['China', 'Indonesia', 'Nigeria'],
        'food': 'Paella',
        'foods': ['Gnocchi', 'Gyro', 'Posole'],
    },
    {
        'name': 'Salsa',
        'category': '',
        'size': '100',
        'calories': '29',
        'protein': '1.52',
        'carbs': '6.64',
        'fat': '0.17',
        'sat_fat': '0.021',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '1.9',
        'sugar': '4.01',
        'added_sugar': '0',
        'vitamin_a': '461.00',
        'vitamin_b': '0.00',
        'vitamin_c': '1.9',
        'vitamin_d': '0.00',
        'vitamin_e': '1.28',
        'calcium': '30.00',
        'iron': '0.42',
        'potassium': '275.00',
        'sodium': '711.00',
        'fact': 'Salse translates to sauce in Spanish',
        'fiction': ['Salsa is traditionally eaten with a spoon and fork', 'Salsa is believed to have magical healing properties for broken bones', 'Salsa is the most popular beverage in Mexico'],
        'export': 'United States',
        'exports': ['China', 'Mexico', 'Spain'],
        'import': 'Peru',
        'imports': ['United States', 'Mexico', 'Guatemala'],
        'food': 'Tacos',
        'foods': ['Posole', 'Mole', 'Cuy'],
    },
    {
        'name': 'Tortilla',
        'category': '',
        'size': '100',
        'calories': '218',
        'protein': '5.70',
        'carbs': '44.64',
        'fat': '2.85',
        'sat_fat': '0.453',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '6.3',
        'sugar': '0.88',
        'added_sugar': '0',
        'vitamin_a': '2.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.28',
        'calcium': '81.00',
        'iron': '1.23',
        'potassium': '186.00',
        'sodium': '45.00',
        'fact': 'Corn tortillas are naturally gluten-free',
        'fiction': ['Tortilla comes from the Latin word tortus, meaning twisted', 'Tortillas were originally used as roofing material', 'Traditional tortillas are square-shaped'],
        'export': 'Mexico',
        'exports': ['United States', 'Ecuador', 'Spain'],
        'import': 'United States',
        'imports': ['Panama', 'Mexico', 'Nicaragua'],
        'food': 'Burrito',
        'foods': ['Calzone', 'Ceviche', 'Shakshuka'],
    }
]