[
    {
        "name": "Apple",
        "category": "",
        "size": "100",
        "calories": "57",
        "protein": "0.25",
        "carbs": "13.68",
        "fat": "0.12",
        "sat_fat": "0",
        "trans_fat": "0",
        "cholesterol": "0",
        "fiber": "2.3",
        "sugar": "10.37",
        "added_sugar": "0",
        "vitamin_a": "28.00",
        "vitamin_b": "0",
        "vitamin_c": "0",
        "vitamin_d": "0",
        "vitamin_e": "0.18",
        "calcium": "7.00",
        "iron": "0.12",
        "potassium": "108.00",
        "sodium": "1.00"
    },
    {
        "name": "Banana",
        "category": "",
        "size": "100",
        "calories": "89",
        "protein": "1.09",
        "carbs": "22.84",
        "fat": "0.33",
        "sat_fat": "0.112",
        "trans_fat": "0",
        "cholesterol": "0",
        "fiber": "2.6",
        "sugar": "12.23",
        "added_sugar": "0",
        "vitamin_a": "64.00",
        "vitamin_b": "0.00",
        "vitamin_c": "8.7",
        "vitamin_d": "0.00",
        "vitamin_e": "0.10",
        "calcium": "5.00",
        "iron": "0.26",
        "potassium": "358.00",
        "sodium": "1.00"
    },
    {
        "name": "Bread",
        "category": "",
        "size": "100",
        "calories": "267",
        "protein": "10.72",
        "carbs": "48.68",
        "fat": "3.24",
        "sat_fat": "0.777",
        "trans_fat": "0",
        "cholesterol": "0",
        "fiber": "4.0",
        "sugar": "5.91",
        "added_sugar": "0",
        "vitamin_a": "2.00",
        "vitamin_b": "0.00",
        "vitamin_c": "0.2",
        "vitamin_d": "0.00",
        "vitamin_e": "0.19",
        "calcium": "133.00",
        "iron": "3.49",
        "potassium": "177.00",
        "sodium": "508.00"
    },
    {
        "name": "Cheerios",
        "category": "",
        "size": "100",
        "calories": "376",
        "protein": "12.09",
        "carbs": "73.23",
        "fat": "6.73",
        "sat_fat": "1.500",
        "trans_fat": "0",
        "cholesterol": "0",
        "fiber": "9.4",
        "sugar": "4.36",
        "added_sugar": "0",
        "vitamin_a": "3299.00",
        "vitamin_b": "6.77",
        "vitamin_c": "21.6",
        "vitamin_d": "136.00",
        "vitamin_e": "0.65",
        "calcium": "401.00",
        "iron": "33.17",
        "potassium": "641.00",
        "sodium": "497.00"
    },
    {
        "name": "Egg (Scrambled)",
        "category": "",
        "size": "100",
        "calories": "149",
        "protein": "9.99",
        "carbs": "1.61",
        "fat": "10.98",
        "sat_fat": "3.331",
        "trans_fat": "0",
        "cholesterol": "277",
        "fiber": "0.0",
        "sugar": "1.39",
        "added_sugar": "0",
        "vitamin_a": "578.00",
        "vitamin_b": "0.76",
        "vitamin_c": "0.0",
        "vitamin_d": "72.00",
        "vitamin_e": "1.15",
        "calcium": "66.00",
        "iron": "1.31",
        "potassium": "132.00",
        "sodium": "145.00"
    },
    {
        "name": "Greek Yogurt",
        "category": "",
        "size": "100",
        "calories": "97",
        "protein": "9.00",
        "carbs": "3.98",
        "fat": "5.00",
        "sat_fat": "2.395",
        "trans_fat": "0",
        "cholesterol": "13",
        "fiber": "0.0",
        "sugar": "4.00",
        "added_sugar": "0",
        "vitamin_a": "15.00",
        "vitamin_b": "0.75",
        "vitamin_c": "0.0",
        "vitamin_d": "0.00",
        "vitamin_e": "0.01",
        "calcium": "100.00",
        "iron": "0.00",
        "potassium": "141.00",
        "sodium": "35.00"
    },
    {
        "name": "Orange",
        "category": "",
        "size": "100",
        "calories": "49",
        "protein": "0.91",
        "carbs": "12.54",
        "fat": "0.15",
        "sat_fat": "0.017",
        "trans_fat": "0",
        "cholesterol": "0",
        "fiber": "2.2",
        "sugar": "8.50",
        "added_sugar": "0",
        "vitamin_a": "247.00",
        "vitamin_b": "0.00",
        "vitamin_c": "59.1",
        "vitamin_d": "0.00",
        "vitamin_e": "0.15",
        "calcium": "43.00",
        "iron": "0.13",
        "potassium": "166.00",
        "sodium": "1.00"
    }
]