export const food_data = [
    {
        'name': 'Apple',
        'category': '',
        'size': '100',
        'calories': '57',
        'protein': '0.25',
        'carbs': '13.68',
        'fat': '0.12',
        'sat_fat': '0',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '2.3',
        'sugar': '10.37',
        'added_sugar': '0',
        'vitamin_a': '28.00',
        'vitamin_b': '0',
        'vitamin_c': '0',
        'vitamin_d': '0',
        'vitamin_e': '0.18',
        'calcium': '7.00',
        'iron': '0.12',
        'potassium': '108.00',
        'sodium': '1.00'
    },
    {
        'name': 'Banana',
        'category': '',
        'size': '100',
        'calories': '89',
        'protein': '1.09',
        'carbs': '22.84',
        'fat': '0.33',
        'sat_fat': '0.112',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '2.6',
        'sugar': '12.23',
        'added_sugar': '0',
        'vitamin_a': '64.00',
        'vitamin_b': '0.00',
        'vitamin_c': '8.7',
        'vitamin_d': '0.00',
        'vitamin_e': '0.10',
        'calcium': '5.00',
        'iron': '0.26',
        'potassium': '358.00',
        'sodium': '1.00'
    },
    {
        'name': 'Bread',
        'category': '',
        'size': '100',
        'calories': '267',
        'protein': '10.72',
        'carbs': '48.68',
        'fat': '3.24',
        'sat_fat': '0.777',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '4.0',
        'sugar': '5.91',
        'added_sugar': '0',
        'vitamin_a': '2.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.2',
        'vitamin_d': '0.00',
        'vitamin_e': '0.19',
        'calcium': '133.00',
        'iron': '3.49',
        'potassium': '177.00',
        'sodium': '508.00'
    },
    {
        'name': 'Butter (Salted)',
        'category': '',
        'size': '100',
        'calories': '717',
        'protein': '0.85',
        'carbs': '0.06',
        'fat': '81.11',
        'sat_fat': '51.368',
        'trans_fat': '0',
        'cholesterol': '215',
        'fiber': '0.0',
        'sugar': '0.06',
        'added_sugar': '0',
        'vitamin_a': '2499.00',
        'vitamin_b': '0.17',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '2.32',
        'calcium': '24.00',
        'iron': '0.02',
        'potassium': '24.00',
        'sodium': '643.00'
    },
    {
        'name': 'Cheerios',
        'category': '',
        'size': '100',
        'calories': '376',
        'protein': '12.09',
        'carbs': '73.23',
        'fat': '6.73',
        'sat_fat': '1.500',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '9.4',
        'sugar': '4.36',
        'added_sugar': '0',
        'vitamin_a': '3299.00',
        'vitamin_b': '6.77',
        'vitamin_c': '21.6',
        'vitamin_d': '136.00',
        'vitamin_e': '0.65',
        'calcium': '401.00',
        'iron': '33.17',
        'potassium': '641.00',
        'sodium': '497.00'
    },
    {
        'name': 'Chicken Tenders',
        'category': '',
        'size': '100',
        'calories': '271',
        'protein': '19.22',
        'carbs': '17.25',
        'fat': '13.95',
        'sat_fat': '2.493',
        'trans_fat': '0',
        'cholesterol': '48',
        'fiber': '1.2',
        'sugar': '0.40',
        'added_sugar': '0',
        'vitamin_a': '11.00',
        'vitamin_b': '0.16',
        'vitamin_c': '1.1',
        'vitamin_d': '7.00',
        'vitamin_e': '3.17',
        'calcium': '17.00',
        'iron': '0.73',
        'potassium': '373.00',
        'sodium': '769.00'
    },
    {
        'name': 'Egg (Scrambled)',
        'category': '',
        'size': '100',
        'calories': '149',
        'protein': '9.99',
        'carbs': '1.61',
        'fat': '10.98',
        'sat_fat': '3.331',
        'trans_fat': '0',
        'cholesterol': '277',
        'fiber': '0.0',
        'sugar': '1.39',
        'added_sugar': '0',
        'vitamin_a': '578.00',
        'vitamin_b': '0.76',
        'vitamin_c': '0.0',
        'vitamin_d': '72.00',
        'vitamin_e': '1.15',
        'calcium': '66.00',
        'iron': '1.31',
        'potassium': '132.00',
        'sodium': '145.00'
    },
    {
        'name': 'Greek Yogurt',
        'category': '',
        'size': '100',
        'calories': '97',
        'protein': '9.00',
        'carbs': '3.98',
        'fat': '5.00',
        'sat_fat': '2.395',
        'trans_fat': '0',
        'cholesterol': '13',
        'fiber': '0.0',
        'sugar': '4.00',
        'added_sugar': '0',
        'vitamin_a': '15.00',
        'vitamin_b': '0.75',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.01',
        'calcium': '100.00',
        'iron': '0.00',
        'potassium': '141.00',
        'sodium': '35.00'
    },
    {
        'name': 'Ground Beef',
        'category': '',
        'size': '100',
        'calories': '198',
        'protein': '19.42',
        'carbs': '0.00',
        'fat': '12.73',
        'sat_fat': '5.335',
        'trans_fat': '0',
        'cholesterol': '62',
        'fiber': '0.0',
        'sugar': '0.00',
        'added_sugar': '0',
        'vitamin_a': '0.00',
        'vitamin_b': '1.97',
        'vitamin_c': '0.0',
        'vitamin_d': '0',
        'vitamin_e': '0.35',
        'calcium': '12.00',
        'iron': '1.99',
        'potassium': '289.00',
        'sodium': '68.00'
    },
    {
        'name': 'Hummus',
        'category': '',
        'size': '100',
        'calories': '177',
        'protein': '4.86',
        'carbs': '20.12',
        'fat': '8.59',
        'sat_fat': '1.141',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '4.0',
        'sugar': '0.27',
        'added_sugar': '0',
        'vitamin_a': '5.00',
        'vitamin_b': '0.00',
        'vitamin_c': '7.9',
        'vitamin_d': '0.00',
        'vitamin_e': '0.75',
        'calcium': '49.00',
        'iron': '1.56',
        'potassium': '173.00',
        'sodium': '242.00'
    },
    {
        'name': 'Kimchi',
        'category': '',
        'size': '100',
        'calories': '15',
        'protein': '1.10',
        'carbs': '2.40',
        'fat': '0.50',
        'sat_fat': '0.067',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '1.6',
        'sugar': '1.06',
        'added_sugar': '0',
        'vitamin_a': '93.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.11',
        'calcium': '33.00',
        'iron': '2.50',
        'potassium': '151.00',
        'sodium': '498.00'
    },
    {
        'name': 'M&Ms (Milk Chocolate)',
        'category': '',
        'size': '100',
        'calories': '492',
        'protein': '4.33',
        'carbs': '71.19',
        'fat': '21.13',
        'sat_fat': '13.080',
        'trans_fat': '0',
        'cholesterol': '14',
        'fiber': '2.8',
        'sugar': '63.68',
        'added_sugar': '0',
        'vitamin_a': '187.00',
        'vitamin_b': '0.53',
        'vitamin_c': '0.5',
        'vitamin_d': '0.00',
        'vitamin_e': '0.36',
        'calcium': '105.00',
        'iron': '1.11',
        'potassium': '261.00',
        'sodium': '61.00'
    },
    {
        'name': 'M&Ms (Peanut)',
        'category': '',
        'size': '100',
        'calories': '515',
        'protein': '9.57',
        'carbs': '60.48',
        'fat': '26.13',
        'sat_fat': '10.169',
        'trans_fat': '0',
        'cholesterol': '8',
        'fiber': '3.7',
        'sugar': '50.75',
        'added_sugar': '0',
        'vitamin_a': '74.00',
        'vitamin_b': '0.32',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '2.85',
        'calcium': '102.00',
        'iron': '1.16',
        'potassium': '347.00',
        'sodium': '50.00'
    },
    {
        'name': 'Orange',
        'category': '',
        'size': '100',
        'calories': '49',
        'protein': '0.91',
        'carbs': '12.54',
        'fat': '0.15',
        'sat_fat': '0.017',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '2.2',
        'sugar': '8.50',
        'added_sugar': '0',
        'vitamin_a': '247.00',
        'vitamin_b': '0.00',
        'vitamin_c': '59.1',
        'vitamin_d': '0.00',
        'vitamin_e': '0.15',
        'calcium': '43.00',
        'iron': '0.13',
        'potassium': '166.00',
        'sodium': '1.00'
    },
    {
        'name': 'Pasta (Dry)',
        'category': '',
        'size': '100',
        'calories': '371',
        'protein': '13.04',
        'carbs': '74.67',
        'fat': '1.51',
        'sat_fat': '0.277',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '3.2',
        'sugar': '2.67',
        'added_sugar': '0',
        'vitamin_a': '0.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.11',
        'calcium': '21.00',
        'iron': '1.30',
        'potassium': '223.00',
        'sodium': '6.00'
    },
    {
        'name': 'Rice (Brown, Cooked)',
        'category': '',
        'size': '100',
        'calories': '112',
        'protein': '2.32',
        'carbs': '23.51',
        'fat': '0.83',
        'sat_fat': '0.165',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '1.8',
        'sugar': '0',
        'added_sugar': '0',
        'vitamin_a': '0.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0',
        'calcium': '10.00',
        'iron': '0.53',
        'potassium': '79.00',
        'sodium': '1.00'
    },
    {
        'name': 'Rice (White, Cooked)',
        'category': '',
        'size': '100',
        'calories': '130',
        'protein': '2.36',
        'carbs': '28.73',
        'fat': '0.19',
        'sat_fat': '0.051',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '0',
        'sugar': '0',
        'added_sugar': '0',
        'vitamin_a': '0',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0',
        'calcium': '1.00',
        'iron': '0.20',
        'potassium': '26.00',
        'sodium': '0.00'
    },
    {
        'name': 'Salsa',
        'category': '',
        'size': '100',
        'calories': '29',
        'protein': '1.52',
        'carbs': '6.64',
        'fat': '0.17',
        'sat_fat': '0.021',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '1.9',
        'sugar': '4.01',
        'added_sugar': '0',
        'vitamin_a': '461.00',
        'vitamin_b': '0.00',
        'vitamin_c': '1.9',
        'vitamin_d': '0.00',
        'vitamin_e': '1.28',
        'calcium': '30.00',
        'iron': '0.42',
        'potassium': '275.00',
        'sodium': '711.00'
    },
    {
        'name': 'Tortilla',
        'category': '',
        'size': '100',
        'calories': '218',
        'protein': '5.70',
        'carbs': '44.64',
        'fat': '2.85',
        'sat_fat': '0.453',
        'trans_fat': '0',
        'cholesterol': '0',
        'fiber': '6.3',
        'sugar': '0.88',
        'added_sugar': '0',
        'vitamin_a': '2.00',
        'vitamin_b': '0.00',
        'vitamin_c': '0.0',
        'vitamin_d': '0.00',
        'vitamin_e': '0.28',
        'calcium': '81.00',
        'iron': '1.23',
        'potassium': '186.00',
        'sodium': '45.00'
    }
]